import type { Patient } from "./types";
const gap = (
  id: string,
  type: string,
  condition: string,
  due: string,
  priority: "High" | "Medium" | "Low" = "High",
) => ({
  id,
  type,
  condition,
  due,
  status: "Open" as const,
  priority,
  history: [{ label: "Potential care gap detected", date: "2026-07-01" }],
});
export const patients: Patient[] = [
  {
    id: "PH-20418",
    name: "Maria Collins",
    age: 58,
    conditions: ["Diabetes", "Hypertension"],
    risk: "High",
    cohorts: ["High Diabetes Risk", "Medication Adherence Risk"],
    manager: "Unassigned",
    lastEncounter: "2026-06-30",
    lastContact: "2026-06-18",
    medicationRisk: true,
    edVisits: 2,
    admissions: 0,
    status: "Unmanaged",
    gaps: [gap("G-101", "Diabetes Review", "Diabetes", "2026-07-03")],
    signals: [
      {
        title: "Rising synthetic HbA1c trend",
        evidence: "7.4% → 8.6% across two demo records",
        source: "Laboratory Record",
        date: "2026-06-28",
      },
      {
        title: "Potential refill gap",
        evidence: "38 days since expected refill",
        source: "Pharmacy History",
        date: "2026-07-10",
      },
      {
        title: "Overdue review",
        evidence: "Follow-up overdue by 42 days",
        source: "Appointment Record",
        date: "2026-07-03",
      },
    ],
    timeline: [
      {
        date: "2026-07-10",
        type: "Pharmacy",
        detail: "Potential refill gap detected",
      },
      { date: "2026-06-28", type: "Lab", detail: "Synthetic HbA1c 8.6%" },
      { date: "2026-06-18", type: "Outreach", detail: "Portal reminder sent" },
    ],
  },
  {
    id: "PH-19872",
    name: "James Turner",
    age: 71,
    conditions: ["Cardiovascular", "Heart Failure"],
    risk: "Priority Review",
    cohorts: ["High Readmission Risk", "High Utilization"],
    manager: "Olivia Bennett",
    lastEncounter: "2026-08-02",
    lastContact: "2026-08-04",
    medicationRisk: true,
    edVisits: 3,
    admissions: 2,
    status: "Active Management",
    gaps: [
      gap("G-102", "Post-discharge Follow-up", "Readmission", "2026-08-09"),
      gap("G-103", "Medication Review", "Cardiovascular", "2026-08-07"),
    ],
    signals: [
      {
        title: "Recent repeat admission",
        evidence: "2 admissions in 90 days",
        source: "Encounter Data",
        date: "2026-08-02",
      },
      {
        title: "Follow-up missing",
        evidence: "No appointment within demo follow-up window",
        source: "Appointment Record",
        date: "2026-08-09",
      },
    ],
    timeline: [
      {
        date: "2026-08-02",
        type: "Admission",
        detail: "Discharged after 4-day synthetic stay",
      },
      {
        date: "2026-06-11",
        type: "Admission",
        detail: "Cardiovascular admission",
      },
    ],
  },
  {
    id: "PH-21703",
    name: "Robert Evans",
    age: 66,
    conditions: ["Hypertension"],
    risk: "High",
    cohorts: ["Uncontrolled Hypertension"],
    manager: "Sofia Malik",
    lastEncounter: "2026-07-22",
    lastContact: "2026-06-25",
    medicationRisk: false,
    edVisits: 1,
    admissions: 0,
    status: "Unmanaged",
    gaps: [gap("G-104", "Blood Pressure Review", "Hypertension", "2026-07-15")],
    signals: [
      {
        title: "Repeated elevated synthetic BP",
        evidence: "Three readings above configured demo threshold",
        source: "EHR Observations",
        date: "2026-07-22",
      },
      {
        title: "Review overdue",
        evidence: "No recent monitoring review",
        source: "Appointment Record",
        date: "2026-07-15",
      },
    ],
    timeline: [
      { date: "2026-07-22", type: "Encounter", detail: "Synthetic BP 166/96" },
      {
        date: "2026-06-25",
        type: "Outreach",
        detail: "Phone contact completed",
      },
    ],
  },
  {
    id: "PH-22146",
    name: "Aisha Khan",
    age: 54,
    conditions: ["Cardiovascular"],
    risk: "High",
    cohorts: ["Cardiovascular Screening Gap"],
    manager: "Noah Williams",
    lastEncounter: "2026-05-18",
    lastContact: "2026-05-02",
    medicationRisk: false,
    edVisits: 0,
    admissions: 0,
    status: "Unmanaged",
    gaps: [
      gap("G-105", "Cardiovascular Review", "Cardiovascular", "2026-06-01"),
    ],
    signals: [
      {
        title: "Preventive screening gap",
        evidence: "Review overdue in demo schedule",
        source: "Screening Record",
        date: "2026-06-01",
      },
    ],
    timeline: [
      {
        date: "2026-05-18",
        type: "Encounter",
        detail: "Primary care encounter",
      },
    ],
  },
  {
    id: "PH-22691",
    name: "Helen Brooks",
    age: 62,
    conditions: ["Diabetes", "Cardiovascular"],
    risk: "Moderate",
    cohorts: ["Cardiovascular Screening Gap"],
    manager: "Olivia Bennett",
    lastEncounter: "2026-07-28",
    lastContact: "2026-07-30",
    medicationRisk: false,
    edVisits: 0,
    admissions: 0,
    status: "Active Management",
    gaps: [
      gap(
        "G-106",
        "Cardiovascular Review",
        "Cardiovascular",
        "2026-07-20",
        "Medium",
      ),
    ],
    signals: [
      {
        title: "Screening due",
        evidence: "No completed review in current demo period",
        source: "Screening Record",
        date: "2026-07-20",
      },
    ],
    timeline: [
      {
        date: "2026-07-30",
        type: "Outreach",
        detail: "Patient portal message opened",
      },
    ],
  },
  {
    id: "PH-23012",
    name: "Daniel Moore",
    age: 76,
    conditions: ["COPD", "Cardiovascular"],
    risk: "Priority Review",
    cohorts: ["High Utilization", "High Readmission Risk"],
    manager: "Unassigned",
    lastEncounter: "2026-08-08",
    lastContact: "2026-05-12",
    medicationRisk: true,
    edVisits: 5,
    admissions: 2,
    status: "Unmanaged",
    gaps: [
      gap("G-107", "Care Plan Missing", "Utilization", "2026-07-01"),
      gap("G-108", "Post-discharge Follow-up", "Readmission", "2026-08-12"),
    ],
    signals: [
      {
        title: "Repeated emergency utilization",
        evidence: "5 ED visits in six months",
        source: "Encounter Data",
        date: "2026-08-08",
      },
    ],
    timeline: [
      {
        date: "2026-08-08",
        type: "Emergency",
        detail: "Fifth synthetic ED encounter",
      },
      { date: "2026-07-17", type: "Admission", detail: "Two-day admission" },
    ],
  },
];
export const aggregate = {
  population: 128420,
  diabetes: 4281,
  diabetesOverdue: 742,
  cardioScreening: 6019,
  readmission: 1203,
  adherence: 2417,
  hypertension: 3842,
  highUtilization: 936,
};
export const trend = [
  { month: "Mar", gaps: 11620, closed: 680 },
  { month: "Apr", gaps: 11180, closed: 820 },
  { month: "May", gaps: 10640, closed: 1040 },
  { month: "Jun", gaps: 10120, closed: 1260 },
  { month: "Jul", gaps: 9540, closed: 1510 },
  { month: "Aug", gaps: 9184, closed: 1738 },
];
